<?php
/**
 * CampaignsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcall API
 *
 * A RESTful API (json) to manage your human-powered outbound call campaigns.
 *
 * OpenAPI spec version: 2
 * Contact: support@upcall.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * CampaignsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class CampaignsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createCampaign
     *
     * Create a new campaign.
     *
     */
    public function testCreateCampaign()
    {
    }

    /**
     * Test case for deleteCampaign
     *
     * Delete a campaign.
     *
     */
    public function testDeleteCampaign()
    {
    }

    /**
     * Test case for fetchCampaign
     *
     * Get a specific campaign.
     *
     */
    public function testFetchCampaign()
    {
    }

    /**
     * Test case for fetchCampaigns
     *
     * Get all campaigns.
     *
     */
    public function testFetchCampaigns()
    {
    }

    /**
     * Test case for updateCampaign
     *
     * Update a campaign.
     *
     */
    public function testUpdateCampaign()
    {
    }
}
