<?php
/**
 * ContactsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcall API
 *
 * A RESTful API (json) to manage your human-powered outbound call campaigns.
 *
 * OpenAPI spec version: 2
 * Contact: support@upcall.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContactsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContactsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createContact
     *
     * Add a contact to a campaign.
     *
     */
    public function testCreateContact()
    {
    }

    /**
     * Test case for deleteContact
     *
     * Delete contact.
     *
     */
    public function testDeleteContact()
    {
    }

    /**
     * Test case for fetchContacts
     *
     * Get contacts for a campaign.
     *
     */
    public function testFetchContacts()
    {
    }

    /**
     * Test case for fetchCustomFields
     *
     * Get custom fields.
     *
     */
    public function testFetchCustomFields()
    {
    }

    /**
     * Test case for fetchSpecificContact
     *
     * Get a specific contact.
     *
     */
    public function testFetchSpecificContact()
    {
    }

    /**
     * Test case for updateContact
     *
     * Update a contact.
     *
     */
    public function testUpdateContact()
    {
    }
}
