<?php
/**
 * ContactAttribute
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Upcall API
 *
 * A RESTful API (json) to manage your human-powered outbound call campaigns.
 *
 * OpenAPI spec version: 2
 * Contact: support@upcall.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * ContactAttribute Class Doc Comment
 *
 * @category    Class
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContactAttribute implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ContactAttribute';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'id' => 'string',
        'status' => 'string',
        'first_name' => 'string',
        'last_name' => 'string',
        'notes' => 'string',
        'title' => 'string',
        'urgency' => 'string',
        'company' => 'string',
        'email' => 'string',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'deleted_at' => '\DateTime',
        'timezone' => 'string',
        'number' => 'string',
        'extension' => 'string',
        'website' => 'string',
        'address' => '\Swagger\Client\Model\Address',
        'custom_fields' => '\Swagger\Client\Model\Keyvalue[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerFormats = [
        'id' => null,
        'status' => null,
        'first_name' => null,
        'last_name' => null,
        'notes' => null,
        'title' => null,
        'urgency' => null,
        'company' => null,
        'email' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'deleted_at' => 'date-time',
        'timezone' => null,
        'number' => null,
        'extension' => null,
        'website' => null,
        'address' => null,
        'custom_fields' => null
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'status' => 'status',
        'first_name' => 'first_name',
        'last_name' => 'last_name',
        'notes' => 'notes',
        'title' => 'title',
        'urgency' => 'urgency',
        'company' => 'company',
        'email' => 'email',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'deleted_at' => 'deleted_at',
        'timezone' => 'timezone',
        'number' => 'number',
        'extension' => 'extension',
        'website' => 'website',
        'address' => 'address',
        'custom_fields' => 'custom_fields'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'status' => 'setStatus',
        'first_name' => 'setFirstName',
        'last_name' => 'setLastName',
        'notes' => 'setNotes',
        'title' => 'setTitle',
        'urgency' => 'setUrgency',
        'company' => 'setCompany',
        'email' => 'setEmail',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'deleted_at' => 'setDeletedAt',
        'timezone' => 'setTimezone',
        'number' => 'setNumber',
        'extension' => 'setExtension',
        'website' => 'setWebsite',
        'address' => 'setAddress',
        'custom_fields' => 'setCustomFields'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'status' => 'getStatus',
        'first_name' => 'getFirstName',
        'last_name' => 'getLastName',
        'notes' => 'getNotes',
        'title' => 'getTitle',
        'urgency' => 'getUrgency',
        'company' => 'getCompany',
        'email' => 'getEmail',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'deleted_at' => 'getDeletedAt',
        'timezone' => 'getTimezone',
        'number' => 'getNumber',
        'extension' => 'getExtension',
        'website' => 'getWebsite',
        'address' => 'getAddress',
        'custom_fields' => 'getCustomFields'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    const STATUS_FAILED_TO_REACH = 'failed_to_reach';
    const STATUS_NO_LONGER_CALL = 'no_longer_call';
    const STATUS_MAYBE_INTERESTED = 'maybe_interested';
    const STATUS_READY_FOR_CALL = 'ready_for_call';
    const STATUS_OUTDATED = 'outdated';
    const STATUS_VOICEMAIL = 'voicemail';
    const STATUS_DELETED = 'deleted';
    const STATUS_COMPLETED = 'completed';
    const STATUS_FAILED = 'failed';
    const STATUS_DNC = 'dnc';
    const STATUS_INCOMPLETED = 'incompleted';
    const STATUS_UNTRIED = 'untried';
    const URGENCY_ASAP = 'asap';
    const URGENCY_SAME_DAY = 'same_day';
    const URGENCY_SAME_WEEK = 'same_week';
    const URGENCY_SAME_MONTH = 'same_month';
    const TIMEZONE_AFRICAABIDJAN = 'Africa/Abidjan';
    const TIMEZONE_AFRICAACCRA = 'Africa/Accra';
    const TIMEZONE_AFRICAADDIS_ABABA = 'Africa/Addis_Ababa';
    const TIMEZONE_AFRICAALGIERS = 'Africa/Algiers';
    const TIMEZONE_AFRICAASMARA = 'Africa/Asmara';
    const TIMEZONE_AFRICAASMERA = 'Africa/Asmera';
    const TIMEZONE_AFRICABAMAKO = 'Africa/Bamako';
    const TIMEZONE_AFRICABANGUI = 'Africa/Bangui';
    const TIMEZONE_AFRICABANJUL = 'Africa/Banjul';
    const TIMEZONE_AFRICABISSAU = 'Africa/Bissau';
    const TIMEZONE_AFRICABLANTYRE = 'Africa/Blantyre';
    const TIMEZONE_AFRICABRAZZAVILLE = 'Africa/Brazzaville';
    const TIMEZONE_AFRICABUJUMBURA = 'Africa/Bujumbura';
    const TIMEZONE_AFRICACAIRO = 'Africa/Cairo';
    const TIMEZONE_AFRICACASABLANCA = 'Africa/Casablanca';
    const TIMEZONE_AFRICACEUTA = 'Africa/Ceuta';
    const TIMEZONE_AFRICACONAKRY = 'Africa/Conakry';
    const TIMEZONE_AFRICADAKAR = 'Africa/Dakar';
    const TIMEZONE_AFRICADAR_ES_SALAAM = 'Africa/Dar_es_Salaam';
    const TIMEZONE_AFRICADJIBOUTI = 'Africa/Djibouti';
    const TIMEZONE_AFRICADOUALA = 'Africa/Douala';
    const TIMEZONE_AFRICAEL_AAIUN = 'Africa/El_Aaiun';
    const TIMEZONE_AFRICAFREETOWN = 'Africa/Freetown';
    const TIMEZONE_AFRICAGABORONE = 'Africa/Gaborone';
    const TIMEZONE_AFRICAHARARE = 'Africa/Harare';
    const TIMEZONE_AFRICAJOHANNESBURG = 'Africa/Johannesburg';
    const TIMEZONE_AFRICAJUBA = 'Africa/Juba';
    const TIMEZONE_AFRICAKAMPALA = 'Africa/Kampala';
    const TIMEZONE_AFRICAKHARTOUM = 'Africa/Khartoum';
    const TIMEZONE_AFRICAKIGALI = 'Africa/Kigali';
    const TIMEZONE_AFRICAKINSHASA = 'Africa/Kinshasa';
    const TIMEZONE_AFRICALAGOS = 'Africa/Lagos';
    const TIMEZONE_AFRICALIBREVILLE = 'Africa/Libreville';
    const TIMEZONE_AFRICALOME = 'Africa/Lome';
    const TIMEZONE_AFRICALUANDA = 'Africa/Luanda';
    const TIMEZONE_AFRICALUBUMBASHI = 'Africa/Lubumbashi';
    const TIMEZONE_AFRICALUSAKA = 'Africa/Lusaka';
    const TIMEZONE_AFRICAMALABO = 'Africa/Malabo';
    const TIMEZONE_AFRICAMAPUTO = 'Africa/Maputo';
    const TIMEZONE_AFRICAMASERU = 'Africa/Maseru';
    const TIMEZONE_AFRICAMBABANE = 'Africa/Mbabane';
    const TIMEZONE_AFRICAMOGADISHU = 'Africa/Mogadishu';
    const TIMEZONE_AFRICAMONROVIA = 'Africa/Monrovia';
    const TIMEZONE_AFRICANAIROBI = 'Africa/Nairobi';
    const TIMEZONE_AFRICANDJAMENA = 'Africa/Ndjamena';
    const TIMEZONE_AFRICANIAMEY = 'Africa/Niamey';
    const TIMEZONE_AFRICANOUAKCHOTT = 'Africa/Nouakchott';
    const TIMEZONE_AFRICAOUAGADOUGOU = 'Africa/Ouagadougou';
    const TIMEZONE_AFRICAPORTO_NOVO = 'Africa/Porto-Novo';
    const TIMEZONE_AFRICASAO_TOME = 'Africa/Sao_Tome';
    const TIMEZONE_AFRICATIMBUKTU = 'Africa/Timbuktu';
    const TIMEZONE_AFRICATRIPOLI = 'Africa/Tripoli';
    const TIMEZONE_AFRICATUNIS = 'Africa/Tunis';
    const TIMEZONE_AFRICAWINDHOEK = 'Africa/Windhoek';
    const TIMEZONE_AMERICAADAK = 'America/Adak';
    const TIMEZONE_AMERICAANCHORAGE = 'America/Anchorage';
    const TIMEZONE_AMERICAANGUILLA = 'America/Anguilla';
    const TIMEZONE_AMERICAANTIGUA = 'America/Antigua';
    const TIMEZONE_AMERICAARAGUAINA = 'America/Araguaina';
    const TIMEZONE_AMERICAARGENTINABUENOS_AIRES = 'America/Argentina/Buenos_Aires';
    const TIMEZONE_AMERICAARGENTINACATAMARCA = 'America/Argentina/Catamarca';
    const TIMEZONE_AMERICAARGENTINACOMOD_RIVADAVIA = 'America/Argentina/ComodRivadavia';
    const TIMEZONE_AMERICAARGENTINACORDOBA = 'America/Argentina/Cordoba';
    const TIMEZONE_AMERICAARGENTINAJUJUY = 'America/Argentina/Jujuy';
    const TIMEZONE_AMERICAARGENTINALA_RIOJA = 'America/Argentina/La_Rioja';
    const TIMEZONE_AMERICAARGENTINAMENDOZA = 'America/Argentina/Mendoza';
    const TIMEZONE_AMERICAARGENTINARIO_GALLEGOS = 'America/Argentina/Rio_Gallegos';
    const TIMEZONE_AMERICAARGENTINASALTA = 'America/Argentina/Salta';
    const TIMEZONE_AMERICAARGENTINASAN_JUAN = 'America/Argentina/San_Juan';
    const TIMEZONE_AMERICAARGENTINASAN_LUIS = 'America/Argentina/San_Luis';
    const TIMEZONE_AMERICAARGENTINATUCUMAN = 'America/Argentina/Tucuman';
    const TIMEZONE_AMERICAARGENTINAUSHUAIA = 'America/Argentina/Ushuaia';
    const TIMEZONE_AMERICAARUBA = 'America/Aruba';
    const TIMEZONE_AMERICAASUNCION = 'America/Asuncion';
    const TIMEZONE_AMERICAATIKOKAN = 'America/Atikokan';
    const TIMEZONE_AMERICAATKA = 'America/Atka';
    const TIMEZONE_AMERICABAHIA = 'America/Bahia';
    const TIMEZONE_AMERICABAHIA_BANDERAS = 'America/Bahia_Banderas';
    const TIMEZONE_AMERICABARBADOS = 'America/Barbados';
    const TIMEZONE_AMERICABELEM = 'America/Belem';
    const TIMEZONE_AMERICABELIZE = 'America/Belize';
    const TIMEZONE_AMERICABLANC_SABLON = 'America/Blanc-Sablon';
    const TIMEZONE_AMERICABOA_VISTA = 'America/Boa_Vista';
    const TIMEZONE_AMERICABOGOTA = 'America/Bogota';
    const TIMEZONE_AMERICABOISE = 'America/Boise';
    const TIMEZONE_AMERICABUENOS_AIRES = 'America/Buenos_Aires';
    const TIMEZONE_AMERICACAMBRIDGE_BAY = 'America/Cambridge_Bay';
    const TIMEZONE_AMERICACAMPO_GRANDE = 'America/Campo_Grande';
    const TIMEZONE_AMERICACANCUN = 'America/Cancun';
    const TIMEZONE_AMERICACARACAS = 'America/Caracas';
    const TIMEZONE_AMERICACATAMARCA = 'America/Catamarca';
    const TIMEZONE_AMERICACAYENNE = 'America/Cayenne';
    const TIMEZONE_AMERICACAYMAN = 'America/Cayman';
    const TIMEZONE_AMERICACHICAGO = 'America/Chicago';
    const TIMEZONE_AMERICACHIHUAHUA = 'America/Chihuahua';
    const TIMEZONE_AMERICACORAL_HARBOUR = 'America/Coral_Harbour';
    const TIMEZONE_AMERICACORDOBA = 'America/Cordoba';
    const TIMEZONE_AMERICACOSTA_RICA = 'America/Costa_Rica';
    const TIMEZONE_AMERICACRESTON = 'America/Creston';
    const TIMEZONE_AMERICACUIABA = 'America/Cuiaba';
    const TIMEZONE_AMERICACURACAO = 'America/Curacao';
    const TIMEZONE_AMERICADANMARKSHAVN = 'America/Danmarkshavn';
    const TIMEZONE_AMERICADAWSON = 'America/Dawson';
    const TIMEZONE_AMERICADAWSON_CREEK = 'America/Dawson_Creek';
    const TIMEZONE_AMERICADENVER = 'America/Denver';
    const TIMEZONE_AMERICADETROIT = 'America/Detroit';
    const TIMEZONE_AMERICADOMINICA = 'America/Dominica';
    const TIMEZONE_AMERICAEDMONTON = 'America/Edmonton';
    const TIMEZONE_AMERICAEIRUNEPE = 'America/Eirunepe';
    const TIMEZONE_AMERICAEL_SALVADOR = 'America/El_Salvador';
    const TIMEZONE_AMERICAENSENADA = 'America/Ensenada';
    const TIMEZONE_AMERICAFORT_NELSON = 'America/Fort_Nelson';
    const TIMEZONE_AMERICAFORT_WAYNE = 'America/Fort_Wayne';
    const TIMEZONE_AMERICAFORTALEZA = 'America/Fortaleza';
    const TIMEZONE_AMERICAGLACE_BAY = 'America/Glace_Bay';
    const TIMEZONE_AMERICAGODTHAB = 'America/Godthab';
    const TIMEZONE_AMERICAGOOSE_BAY = 'America/Goose_Bay';
    const TIMEZONE_AMERICAGRAND_TURK = 'America/Grand_Turk';
    const TIMEZONE_AMERICAGRENADA = 'America/Grenada';
    const TIMEZONE_AMERICAGUADELOUPE = 'America/Guadeloupe';
    const TIMEZONE_AMERICAGUATEMALA = 'America/Guatemala';
    const TIMEZONE_AMERICAGUAYAQUIL = 'America/Guayaquil';
    const TIMEZONE_AMERICAGUYANA = 'America/Guyana';
    const TIMEZONE_AMERICAHALIFAX = 'America/Halifax';
    const TIMEZONE_AMERICAHAVANA = 'America/Havana';
    const TIMEZONE_AMERICAHERMOSILLO = 'America/Hermosillo';
    const TIMEZONE_AMERICAINDIANAINDIANAPOLIS = 'America/Indiana/Indianapolis';
    const TIMEZONE_AMERICAINDIANAKNOX = 'America/Indiana/Knox';
    const TIMEZONE_AMERICAINDIANAMARENGO = 'America/Indiana/Marengo';
    const TIMEZONE_AMERICAINDIANAPETERSBURG = 'America/Indiana/Petersburg';
    const TIMEZONE_AMERICAINDIANATELL_CITY = 'America/Indiana/Tell_City';
    const TIMEZONE_AMERICAINDIANAVEVAY = 'America/Indiana/Vevay';
    const TIMEZONE_AMERICAINDIANAVINCENNES = 'America/Indiana/Vincennes';
    const TIMEZONE_AMERICAINDIANAWINAMAC = 'America/Indiana/Winamac';
    const TIMEZONE_AMERICAINDIANAPOLIS = 'America/Indianapolis';
    const TIMEZONE_AMERICAINUVIK = 'America/Inuvik';
    const TIMEZONE_AMERICAIQALUIT = 'America/Iqaluit';
    const TIMEZONE_AMERICAJAMAICA = 'America/Jamaica';
    const TIMEZONE_AMERICAJUJUY = 'America/Jujuy';
    const TIMEZONE_AMERICAJUNEAU = 'America/Juneau';
    const TIMEZONE_AMERICAKENTUCKYLOUISVILLE = 'America/Kentucky/Louisville';
    const TIMEZONE_AMERICAKENTUCKYMONTICELLO = 'America/Kentucky/Monticello';
    const TIMEZONE_AMERICAKNOX_IN = 'America/Knox_IN';
    const TIMEZONE_AMERICAKRALENDIJK = 'America/Kralendijk';
    const TIMEZONE_AMERICALA_PAZ = 'America/La_Paz';
    const TIMEZONE_AMERICALIMA = 'America/Lima';
    const TIMEZONE_AMERICALOS_ANGELES = 'America/Los_Angeles';
    const TIMEZONE_AMERICALOUISVILLE = 'America/Louisville';
    const TIMEZONE_AMERICALOWER_PRINCES = 'America/Lower_Princes';
    const TIMEZONE_AMERICAMACEIO = 'America/Maceio';
    const TIMEZONE_AMERICAMANAGUA = 'America/Managua';
    const TIMEZONE_AMERICAMANAUS = 'America/Manaus';
    const TIMEZONE_AMERICAMARIGOT = 'America/Marigot';
    const TIMEZONE_AMERICAMARTINIQUE = 'America/Martinique';
    const TIMEZONE_AMERICAMATAMOROS = 'America/Matamoros';
    const TIMEZONE_AMERICAMAZATLAN = 'America/Mazatlan';
    const TIMEZONE_AMERICAMENDOZA = 'America/Mendoza';
    const TIMEZONE_AMERICAMENOMINEE = 'America/Menominee';
    const TIMEZONE_AMERICAMERIDA = 'America/Merida';
    const TIMEZONE_AMERICAMETLAKATLA = 'America/Metlakatla';
    const TIMEZONE_AMERICAMEXICO_CITY = 'America/Mexico_City';
    const TIMEZONE_AMERICAMIQUELON = 'America/Miquelon';
    const TIMEZONE_AMERICAMONCTON = 'America/Moncton';
    const TIMEZONE_AMERICAMONTERREY = 'America/Monterrey';
    const TIMEZONE_AMERICAMONTEVIDEO = 'America/Montevideo';
    const TIMEZONE_AMERICAMONTREAL = 'America/Montreal';
    const TIMEZONE_AMERICAMONTSERRAT = 'America/Montserrat';
    const TIMEZONE_AMERICANASSAU = 'America/Nassau';
    const TIMEZONE_AMERICANEW_YORK = 'America/New_York';
    const TIMEZONE_AMERICANIPIGON = 'America/Nipigon';
    const TIMEZONE_AMERICANOME = 'America/Nome';
    const TIMEZONE_AMERICANORONHA = 'America/Noronha';
    const TIMEZONE_AMERICANORTH_DAKOTABEULAH = 'America/North_Dakota/Beulah';
    const TIMEZONE_AMERICANORTH_DAKOTACENTER = 'America/North_Dakota/Center';
    const TIMEZONE_AMERICANORTH_DAKOTANEW_SALEM = 'America/North_Dakota/New_Salem';
    const TIMEZONE_AMERICAOJINAGA = 'America/Ojinaga';
    const TIMEZONE_AMERICAPANAMA = 'America/Panama';
    const TIMEZONE_AMERICAPANGNIRTUNG = 'America/Pangnirtung';
    const TIMEZONE_AMERICAPARAMARIBO = 'America/Paramaribo';
    const TIMEZONE_AMERICAPHOENIX = 'America/Phoenix';
    const TIMEZONE_AMERICAPORT_AU_PRINCE = 'America/Port-au-Prince';
    const TIMEZONE_AMERICAPORT_OF_SPAIN = 'America/Port_of_Spain';
    const TIMEZONE_AMERICAPORTO_ACRE = 'America/Porto_Acre';
    const TIMEZONE_AMERICAPORTO_VELHO = 'America/Porto_Velho';
    const TIMEZONE_AMERICAPUERTO_RICO = 'America/Puerto_Rico';
    const TIMEZONE_AMERICAPUNTA_ARENAS = 'America/Punta_Arenas';
    const TIMEZONE_AMERICARAINY_RIVER = 'America/Rainy_River';
    const TIMEZONE_AMERICARANKIN_INLET = 'America/Rankin_Inlet';
    const TIMEZONE_AMERICARECIFE = 'America/Recife';
    const TIMEZONE_AMERICAREGINA = 'America/Regina';
    const TIMEZONE_AMERICARESOLUTE = 'America/Resolute';
    const TIMEZONE_AMERICARIO_BRANCO = 'America/Rio_Branco';
    const TIMEZONE_AMERICAROSARIO = 'America/Rosario';
    const TIMEZONE_AMERICASANTA_ISABEL = 'America/Santa_Isabel';
    const TIMEZONE_AMERICASANTAREM = 'America/Santarem';
    const TIMEZONE_AMERICASANTIAGO = 'America/Santiago';
    const TIMEZONE_AMERICASANTO_DOMINGO = 'America/Santo_Domingo';
    const TIMEZONE_AMERICASAO_PAULO = 'America/Sao_Paulo';
    const TIMEZONE_AMERICASCORESBYSUND = 'America/Scoresbysund';
    const TIMEZONE_AMERICASHIPROCK = 'America/Shiprock';
    const TIMEZONE_AMERICASITKA = 'America/Sitka';
    const TIMEZONE_AMERICAST_BARTHELEMY = 'America/St_Barthelemy';
    const TIMEZONE_AMERICAST_JOHNS = 'America/St_Johns';
    const TIMEZONE_AMERICAST_KITTS = 'America/St_Kitts';
    const TIMEZONE_AMERICAST_LUCIA = 'America/St_Lucia';
    const TIMEZONE_AMERICAST_THOMAS = 'America/St_Thomas';
    const TIMEZONE_AMERICAST_VINCENT = 'America/St_Vincent';
    const TIMEZONE_AMERICASWIFT_CURRENT = 'America/Swift_Current';
    const TIMEZONE_AMERICATEGUCIGALPA = 'America/Tegucigalpa';
    const TIMEZONE_AMERICATHULE = 'America/Thule';
    const TIMEZONE_AMERICATHUNDER_BAY = 'America/Thunder_Bay';
    const TIMEZONE_AMERICATIJUANA = 'America/Tijuana';
    const TIMEZONE_AMERICATORONTO = 'America/Toronto';
    const TIMEZONE_AMERICATORTOLA = 'America/Tortola';
    const TIMEZONE_AMERICAVANCOUVER = 'America/Vancouver';
    const TIMEZONE_AMERICAVIRGIN = 'America/Virgin';
    const TIMEZONE_AMERICAWHITEHORSE = 'America/Whitehorse';
    const TIMEZONE_AMERICAWINNIPEG = 'America/Winnipeg';
    const TIMEZONE_AMERICAYAKUTAT = 'America/Yakutat';
    const TIMEZONE_AMERICAYELLOWKNIFE = 'America/Yellowknife';
    const TIMEZONE_ANTARCTICACASEY = 'Antarctica/Casey';
    const TIMEZONE_ANTARCTICADAVIS = 'Antarctica/Davis';
    const TIMEZONE_ANTARCTICADUMONT_D_URVILLE = 'Antarctica/DumontDUrville';
    const TIMEZONE_ANTARCTICAMACQUARIE = 'Antarctica/Macquarie';
    const TIMEZONE_ANTARCTICAMAWSON = 'Antarctica/Mawson';
    const TIMEZONE_ANTARCTICAMC_MURDO = 'Antarctica/McMurdo';
    const TIMEZONE_ANTARCTICAPALMER = 'Antarctica/Palmer';
    const TIMEZONE_ANTARCTICAROTHERA = 'Antarctica/Rothera';
    const TIMEZONE_ANTARCTICASOUTH_POLE = 'Antarctica/South_Pole';
    const TIMEZONE_ANTARCTICASYOWA = 'Antarctica/Syowa';
    const TIMEZONE_ANTARCTICATROLL = 'Antarctica/Troll';
    const TIMEZONE_ANTARCTICAVOSTOK = 'Antarctica/Vostok';
    const TIMEZONE_ARCTICLONGYEARBYEN = 'Arctic/Longyearbyen';
    const TIMEZONE_ASIAADEN = 'Asia/Aden';
    const TIMEZONE_ASIAALMATY = 'Asia/Almaty';
    const TIMEZONE_ASIAAMMAN = 'Asia/Amman';
    const TIMEZONE_ASIAANADYR = 'Asia/Anadyr';
    const TIMEZONE_ASIAAQTAU = 'Asia/Aqtau';
    const TIMEZONE_ASIAAQTOBE = 'Asia/Aqtobe';
    const TIMEZONE_ASIAASHGABAT = 'Asia/Ashgabat';
    const TIMEZONE_ASIAASHKHABAD = 'Asia/Ashkhabad';
    const TIMEZONE_ASIAATYRAU = 'Asia/Atyrau';
    const TIMEZONE_ASIABAGHDAD = 'Asia/Baghdad';
    const TIMEZONE_ASIABAHRAIN = 'Asia/Bahrain';
    const TIMEZONE_ASIABAKU = 'Asia/Baku';
    const TIMEZONE_ASIABANGKOK = 'Asia/Bangkok';
    const TIMEZONE_ASIABARNAUL = 'Asia/Barnaul';
    const TIMEZONE_ASIABEIRUT = 'Asia/Beirut';
    const TIMEZONE_ASIABISHKEK = 'Asia/Bishkek';
    const TIMEZONE_ASIABRUNEI = 'Asia/Brunei';
    const TIMEZONE_ASIACALCUTTA = 'Asia/Calcutta';
    const TIMEZONE_ASIACHITA = 'Asia/Chita';
    const TIMEZONE_ASIACHOIBALSAN = 'Asia/Choibalsan';
    const TIMEZONE_ASIACHONGQING = 'Asia/Chongqing';
    const TIMEZONE_ASIACHUNGKING = 'Asia/Chungking';
    const TIMEZONE_ASIACOLOMBO = 'Asia/Colombo';
    const TIMEZONE_ASIADACCA = 'Asia/Dacca';
    const TIMEZONE_ASIADAMASCUS = 'Asia/Damascus';
    const TIMEZONE_ASIADHAKA = 'Asia/Dhaka';
    const TIMEZONE_ASIADILI = 'Asia/Dili';
    const TIMEZONE_ASIADUBAI = 'Asia/Dubai';
    const TIMEZONE_ASIADUSHANBE = 'Asia/Dushanbe';
    const TIMEZONE_ASIAFAMAGUSTA = 'Asia/Famagusta';
    const TIMEZONE_ASIAGAZA = 'Asia/Gaza';
    const TIMEZONE_ASIAHARBIN = 'Asia/Harbin';
    const TIMEZONE_ASIAHEBRON = 'Asia/Hebron';
    const TIMEZONE_ASIAHO_CHI_MINH = 'Asia/Ho_Chi_Minh';
    const TIMEZONE_ASIAHONG_KONG = 'Asia/Hong_Kong';
    const TIMEZONE_ASIAHOVD = 'Asia/Hovd';
    const TIMEZONE_ASIAIRKUTSK = 'Asia/Irkutsk';
    const TIMEZONE_ASIAISTANBUL = 'Asia/Istanbul';
    const TIMEZONE_ASIAJAKARTA = 'Asia/Jakarta';
    const TIMEZONE_ASIAJAYAPURA = 'Asia/Jayapura';
    const TIMEZONE_ASIAJERUSALEM = 'Asia/Jerusalem';
    const TIMEZONE_ASIAKABUL = 'Asia/Kabul';
    const TIMEZONE_ASIAKAMCHATKA = 'Asia/Kamchatka';
    const TIMEZONE_ASIAKARACHI = 'Asia/Karachi';
    const TIMEZONE_ASIAKASHGAR = 'Asia/Kashgar';
    const TIMEZONE_ASIAKATHMANDU = 'Asia/Kathmandu';
    const TIMEZONE_ASIAKATMANDU = 'Asia/Katmandu';
    const TIMEZONE_ASIAKHANDYGA = 'Asia/Khandyga';
    const TIMEZONE_ASIAKOLKATA = 'Asia/Kolkata';
    const TIMEZONE_ASIAKRASNOYARSK = 'Asia/Krasnoyarsk';
    const TIMEZONE_ASIAKUALA_LUMPUR = 'Asia/Kuala_Lumpur';
    const TIMEZONE_ASIAKUCHING = 'Asia/Kuching';
    const TIMEZONE_ASIAKUWAIT = 'Asia/Kuwait';
    const TIMEZONE_ASIAMACAO = 'Asia/Macao';
    const TIMEZONE_ASIAMACAU = 'Asia/Macau';
    const TIMEZONE_ASIAMAGADAN = 'Asia/Magadan';
    const TIMEZONE_ASIAMAKASSAR = 'Asia/Makassar';
    const TIMEZONE_ASIAMANILA = 'Asia/Manila';
    const TIMEZONE_ASIAMUSCAT = 'Asia/Muscat';
    const TIMEZONE_ASIANICOSIA = 'Asia/Nicosia';
    const TIMEZONE_ASIANOVOKUZNETSK = 'Asia/Novokuznetsk';
    const TIMEZONE_ASIANOVOSIBIRSK = 'Asia/Novosibirsk';
    const TIMEZONE_ASIAOMSK = 'Asia/Omsk';
    const TIMEZONE_ASIAORAL = 'Asia/Oral';
    const TIMEZONE_ASIAPHNOM_PENH = 'Asia/Phnom_Penh';
    const TIMEZONE_ASIAPONTIANAK = 'Asia/Pontianak';
    const TIMEZONE_ASIAPYONGYANG = 'Asia/Pyongyang';
    const TIMEZONE_ASIAQATAR = 'Asia/Qatar';
    const TIMEZONE_ASIAQYZYLORDA = 'Asia/Qyzylorda';
    const TIMEZONE_ASIARANGOON = 'Asia/Rangoon';
    const TIMEZONE_ASIARIYADH = 'Asia/Riyadh';
    const TIMEZONE_ASIASAIGON = 'Asia/Saigon';
    const TIMEZONE_ASIASAKHALIN = 'Asia/Sakhalin';
    const TIMEZONE_ASIASAMARKAND = 'Asia/Samarkand';
    const TIMEZONE_ASIASEOUL = 'Asia/Seoul';
    const TIMEZONE_ASIASHANGHAI = 'Asia/Shanghai';
    const TIMEZONE_ASIASINGAPORE = 'Asia/Singapore';
    const TIMEZONE_ASIASREDNEKOLYMSK = 'Asia/Srednekolymsk';
    const TIMEZONE_ASIATAIPEI = 'Asia/Taipei';
    const TIMEZONE_ASIATASHKENT = 'Asia/Tashkent';
    const TIMEZONE_ASIATBILISI = 'Asia/Tbilisi';
    const TIMEZONE_ASIATEHRAN = 'Asia/Tehran';
    const TIMEZONE_ASIATEL_AVIV = 'Asia/Tel_Aviv';
    const TIMEZONE_ASIATHIMBU = 'Asia/Thimbu';
    const TIMEZONE_ASIATHIMPHU = 'Asia/Thimphu';
    const TIMEZONE_ASIATOKYO = 'Asia/Tokyo';
    const TIMEZONE_ASIATOMSK = 'Asia/Tomsk';
    const TIMEZONE_ASIAUJUNG_PANDANG = 'Asia/Ujung_Pandang';
    const TIMEZONE_ASIAULAANBAATAR = 'Asia/Ulaanbaatar';
    const TIMEZONE_ASIAULAN_BATOR = 'Asia/Ulan_Bator';
    const TIMEZONE_ASIAURUMQI = 'Asia/Urumqi';
    const TIMEZONE_ASIAUST_NERA = 'Asia/Ust-Nera';
    const TIMEZONE_ASIAVIENTIANE = 'Asia/Vientiane';
    const TIMEZONE_ASIAVLADIVOSTOK = 'Asia/Vladivostok';
    const TIMEZONE_ASIAYAKUTSK = 'Asia/Yakutsk';
    const TIMEZONE_ASIAYANGON = 'Asia/Yangon';
    const TIMEZONE_ASIAYEKATERINBURG = 'Asia/Yekaterinburg';
    const TIMEZONE_ASIAYEREVAN = 'Asia/Yerevan';
    const TIMEZONE_ATLANTICAZORES = 'Atlantic/Azores';
    const TIMEZONE_ATLANTICBERMUDA = 'Atlantic/Bermuda';
    const TIMEZONE_ATLANTICCANARY = 'Atlantic/Canary';
    const TIMEZONE_ATLANTICCAPE_VERDE = 'Atlantic/Cape_Verde';
    const TIMEZONE_ATLANTICFAEROE = 'Atlantic/Faeroe';
    const TIMEZONE_ATLANTICFAROE = 'Atlantic/Faroe';
    const TIMEZONE_ATLANTICJAN_MAYEN = 'Atlantic/Jan_Mayen';
    const TIMEZONE_ATLANTICMADEIRA = 'Atlantic/Madeira';
    const TIMEZONE_ATLANTICREYKJAVIK = 'Atlantic/Reykjavik';
    const TIMEZONE_ATLANTICSOUTH_GEORGIA = 'Atlantic/South_Georgia';
    const TIMEZONE_ATLANTICST_HELENA = 'Atlantic/St_Helena';
    const TIMEZONE_ATLANTICSTANLEY = 'Atlantic/Stanley';
    const TIMEZONE_AUSTRALIAACT = 'Australia/ACT';
    const TIMEZONE_AUSTRALIAADELAIDE = 'Australia/Adelaide';
    const TIMEZONE_AUSTRALIABRISBANE = 'Australia/Brisbane';
    const TIMEZONE_AUSTRALIABROKEN_HILL = 'Australia/Broken_Hill';
    const TIMEZONE_AUSTRALIACANBERRA = 'Australia/Canberra';
    const TIMEZONE_AUSTRALIACURRIE = 'Australia/Currie';
    const TIMEZONE_AUSTRALIADARWIN = 'Australia/Darwin';
    const TIMEZONE_AUSTRALIAEUCLA = 'Australia/Eucla';
    const TIMEZONE_AUSTRALIAHOBART = 'Australia/Hobart';
    const TIMEZONE_AUSTRALIALHI = 'Australia/LHI';
    const TIMEZONE_AUSTRALIALINDEMAN = 'Australia/Lindeman';
    const TIMEZONE_AUSTRALIALORD_HOWE = 'Australia/Lord_Howe';
    const TIMEZONE_AUSTRALIAMELBOURNE = 'Australia/Melbourne';
    const TIMEZONE_AUSTRALIANSW = 'Australia/NSW';
    const TIMEZONE_AUSTRALIANORTH = 'Australia/North';
    const TIMEZONE_AUSTRALIAPERTH = 'Australia/Perth';
    const TIMEZONE_AUSTRALIAQUEENSLAND = 'Australia/Queensland';
    const TIMEZONE_AUSTRALIASOUTH = 'Australia/South';
    const TIMEZONE_AUSTRALIASYDNEY = 'Australia/Sydney';
    const TIMEZONE_AUSTRALIATASMANIA = 'Australia/Tasmania';
    const TIMEZONE_AUSTRALIAVICTORIA = 'Australia/Victoria';
    const TIMEZONE_AUSTRALIAWEST = 'Australia/West';
    const TIMEZONE_AUSTRALIAYANCOWINNA = 'Australia/Yancowinna';
    const TIMEZONE_BRAZILACRE = 'Brazil/Acre';
    const TIMEZONE_BRAZILDE_NORONHA = 'Brazil/DeNoronha';
    const TIMEZONE_BRAZILEAST = 'Brazil/East';
    const TIMEZONE_BRAZILWEST = 'Brazil/West';
    const TIMEZONE_CET = 'CET';
    const TIMEZONE_CST6_CDT = 'CST6CDT';
    const TIMEZONE_CANADAATLANTIC = 'Canada/Atlantic';
    const TIMEZONE_CANADACENTRAL = 'Canada/Central';
    const TIMEZONE_CANADAEASTERN = 'Canada/Eastern';
    const TIMEZONE_CANADAMOUNTAIN = 'Canada/Mountain';
    const TIMEZONE_CANADANEWFOUNDLAND = 'Canada/Newfoundland';
    const TIMEZONE_CANADAPACIFIC = 'Canada/Pacific';
    const TIMEZONE_CANADASASKATCHEWAN = 'Canada/Saskatchewan';
    const TIMEZONE_CANADAYUKON = 'Canada/Yukon';
    const TIMEZONE_CHILECONTINENTAL = 'Chile/Continental';
    const TIMEZONE_CHILEEASTER_ISLAND = 'Chile/EasterIsland';
    const TIMEZONE_CUBA = 'Cuba';
    const TIMEZONE_EET = 'EET';
    const TIMEZONE_EST = 'EST';
    const TIMEZONE_EST5_EDT = 'EST5EDT';
    const TIMEZONE_EGYPT = 'Egypt';
    const TIMEZONE_EIRE = 'Eire';
    const TIMEZONE_ETCGMT = 'Etc/GMT';
    const TIMEZONE_ETCGMT0 = 'Etc/GMT+0';
    const TIMEZONE_ETCGMT1 = 'Etc/GMT+1';
    const TIMEZONE_ETCGMT10 = 'Etc/GMT+10';
    const TIMEZONE_ETCGMT11 = 'Etc/GMT+11';
    const TIMEZONE_ETCGMT12 = 'Etc/GMT+12';
    const TIMEZONE_ETCGMT2 = 'Etc/GMT+2';
    const TIMEZONE_ETCGMT3 = 'Etc/GMT+3';
    const TIMEZONE_ETCGMT4 = 'Etc/GMT+4';
    const TIMEZONE_ETCGMT5 = 'Etc/GMT+5';
    const TIMEZONE_ETCGMT6 = 'Etc/GMT+6';
    const TIMEZONE_ETCGMT7 = 'Etc/GMT+7';
    const TIMEZONE_ETCGMT8 = 'Etc/GMT+8';
    const TIMEZONE_ETCGMT9 = 'Etc/GMT+9';
    const TIMEZONE_ETCGMT_0 = 'Etc/GMT-0';
    const TIMEZONE_ETCGMT_1 = 'Etc/GMT-1';
    const TIMEZONE_ETCGMT_10 = 'Etc/GMT-10';
    const TIMEZONE_ETCGMT_11 = 'Etc/GMT-11';
    const TIMEZONE_ETCGMT_12 = 'Etc/GMT-12';
    const TIMEZONE_ETCGMT_13 = 'Etc/GMT-13';
    const TIMEZONE_ETCGMT_14 = 'Etc/GMT-14';
    const TIMEZONE_ETCGMT_2 = 'Etc/GMT-2';
    const TIMEZONE_ETCGMT_3 = 'Etc/GMT-3';
    const TIMEZONE_ETCGMT_4 = 'Etc/GMT-4';
    const TIMEZONE_ETCGMT_5 = 'Etc/GMT-5';
    const TIMEZONE_ETCGMT_6 = 'Etc/GMT-6';
    const TIMEZONE_ETCGMT_7 = 'Etc/GMT-7';
    const TIMEZONE_ETCGMT_8 = 'Etc/GMT-8';
    const TIMEZONE_ETCGMT_9 = 'Etc/GMT-9';
    const TIMEZONE_ETCGMT0 = 'Etc/GMT0';
    const TIMEZONE_ETCGREENWICH = 'Etc/Greenwich';
    const TIMEZONE_ETCUCT = 'Etc/UCT';
    const TIMEZONE_ETCUTC = 'Etc/UTC';
    const TIMEZONE_ETCUNIVERSAL = 'Etc/Universal';
    const TIMEZONE_ETCZULU = 'Etc/Zulu';
    const TIMEZONE_EUROPEAMSTERDAM = 'Europe/Amsterdam';
    const TIMEZONE_EUROPEANDORRA = 'Europe/Andorra';
    const TIMEZONE_EUROPEASTRAKHAN = 'Europe/Astrakhan';
    const TIMEZONE_EUROPEATHENS = 'Europe/Athens';
    const TIMEZONE_EUROPEBELFAST = 'Europe/Belfast';
    const TIMEZONE_EUROPEBELGRADE = 'Europe/Belgrade';
    const TIMEZONE_EUROPEBERLIN = 'Europe/Berlin';
    const TIMEZONE_EUROPEBRATISLAVA = 'Europe/Bratislava';
    const TIMEZONE_EUROPEBRUSSELS = 'Europe/Brussels';
    const TIMEZONE_EUROPEBUCHAREST = 'Europe/Bucharest';
    const TIMEZONE_EUROPEBUDAPEST = 'Europe/Budapest';
    const TIMEZONE_EUROPEBUSINGEN = 'Europe/Busingen';
    const TIMEZONE_EUROPECHISINAU = 'Europe/Chisinau';
    const TIMEZONE_EUROPECOPENHAGEN = 'Europe/Copenhagen';
    const TIMEZONE_EUROPEDUBLIN = 'Europe/Dublin';
    const TIMEZONE_EUROPEGIBRALTAR = 'Europe/Gibraltar';
    const TIMEZONE_EUROPEGUERNSEY = 'Europe/Guernsey';
    const TIMEZONE_EUROPEHELSINKI = 'Europe/Helsinki';
    const TIMEZONE_EUROPEISLE_OF_MAN = 'Europe/Isle_of_Man';
    const TIMEZONE_EUROPEISTANBUL = 'Europe/Istanbul';
    const TIMEZONE_EUROPEJERSEY = 'Europe/Jersey';
    const TIMEZONE_EUROPEKALININGRAD = 'Europe/Kaliningrad';
    const TIMEZONE_EUROPEKIEV = 'Europe/Kiev';
    const TIMEZONE_EUROPEKIROV = 'Europe/Kirov';
    const TIMEZONE_EUROPELISBON = 'Europe/Lisbon';
    const TIMEZONE_EUROPELJUBLJANA = 'Europe/Ljubljana';
    const TIMEZONE_EUROPELONDON = 'Europe/London';
    const TIMEZONE_EUROPELUXEMBOURG = 'Europe/Luxembourg';
    const TIMEZONE_EUROPEMADRID = 'Europe/Madrid';
    const TIMEZONE_EUROPEMALTA = 'Europe/Malta';
    const TIMEZONE_EUROPEMARIEHAMN = 'Europe/Mariehamn';
    const TIMEZONE_EUROPEMINSK = 'Europe/Minsk';
    const TIMEZONE_EUROPEMONACO = 'Europe/Monaco';
    const TIMEZONE_EUROPEMOSCOW = 'Europe/Moscow';
    const TIMEZONE_EUROPENICOSIA = 'Europe/Nicosia';
    const TIMEZONE_EUROPEOSLO = 'Europe/Oslo';
    const TIMEZONE_EUROPEPARIS = 'Europe/Paris';
    const TIMEZONE_EUROPEPODGORICA = 'Europe/Podgorica';
    const TIMEZONE_EUROPEPRAGUE = 'Europe/Prague';
    const TIMEZONE_EUROPERIGA = 'Europe/Riga';
    const TIMEZONE_EUROPEROME = 'Europe/Rome';
    const TIMEZONE_EUROPESAMARA = 'Europe/Samara';
    const TIMEZONE_EUROPESAN_MARINO = 'Europe/San_Marino';
    const TIMEZONE_EUROPESARAJEVO = 'Europe/Sarajevo';
    const TIMEZONE_EUROPESARATOV = 'Europe/Saratov';
    const TIMEZONE_EUROPESIMFEROPOL = 'Europe/Simferopol';
    const TIMEZONE_EUROPESKOPJE = 'Europe/Skopje';
    const TIMEZONE_EUROPESOFIA = 'Europe/Sofia';
    const TIMEZONE_EUROPESTOCKHOLM = 'Europe/Stockholm';
    const TIMEZONE_EUROPETALLINN = 'Europe/Tallinn';
    const TIMEZONE_EUROPETIRANE = 'Europe/Tirane';
    const TIMEZONE_EUROPETIRASPOL = 'Europe/Tiraspol';
    const TIMEZONE_EUROPEULYANOVSK = 'Europe/Ulyanovsk';
    const TIMEZONE_EUROPEUZHGOROD = 'Europe/Uzhgorod';
    const TIMEZONE_EUROPEVADUZ = 'Europe/Vaduz';
    const TIMEZONE_EUROPEVATICAN = 'Europe/Vatican';
    const TIMEZONE_EUROPEVIENNA = 'Europe/Vienna';
    const TIMEZONE_EUROPEVILNIUS = 'Europe/Vilnius';
    const TIMEZONE_EUROPEVOLGOGRAD = 'Europe/Volgograd';
    const TIMEZONE_EUROPEWARSAW = 'Europe/Warsaw';
    const TIMEZONE_EUROPEZAGREB = 'Europe/Zagreb';
    const TIMEZONE_EUROPEZAPOROZHYE = 'Europe/Zaporozhye';
    const TIMEZONE_EUROPEZURICH = 'Europe/Zurich';
    const TIMEZONE_FACTORY = 'Factory';
    const TIMEZONE_GB = 'GB';
    const TIMEZONE_GB_EIRE = 'GB-Eire';
    const TIMEZONE_GMT = 'GMT';
    const TIMEZONE_GMT0 = 'GMT+0';
    const TIMEZONE_GMT_0 = 'GMT-0';
    const TIMEZONE_GMT0 = 'GMT0';
    const TIMEZONE_GREENWICH = 'Greenwich';
    const TIMEZONE_HST = 'HST';
    const TIMEZONE_HONGKONG = 'Hongkong';
    const TIMEZONE_ICELAND = 'Iceland';
    const TIMEZONE_INDIANANTANANARIVO = 'Indian/Antananarivo';
    const TIMEZONE_INDIANCHAGOS = 'Indian/Chagos';
    const TIMEZONE_INDIANCHRISTMAS = 'Indian/Christmas';
    const TIMEZONE_INDIANCOCOS = 'Indian/Cocos';
    const TIMEZONE_INDIANCOMORO = 'Indian/Comoro';
    const TIMEZONE_INDIANKERGUELEN = 'Indian/Kerguelen';
    const TIMEZONE_INDIANMAHE = 'Indian/Mahe';
    const TIMEZONE_INDIANMALDIVES = 'Indian/Maldives';
    const TIMEZONE_INDIANMAURITIUS = 'Indian/Mauritius';
    const TIMEZONE_INDIANMAYOTTE = 'Indian/Mayotte';
    const TIMEZONE_INDIANREUNION = 'Indian/Reunion';
    const TIMEZONE_IRAN = 'Iran';
    const TIMEZONE_ISRAEL = 'Israel';
    const TIMEZONE_JAMAICA = 'Jamaica';
    const TIMEZONE_JAPAN = 'Japan';
    const TIMEZONE_KWAJALEIN = 'Kwajalein';
    const TIMEZONE_LIBYA = 'Libya';
    const TIMEZONE_MET = 'MET';
    const TIMEZONE_MST = 'MST';
    const TIMEZONE_MST7_MDT = 'MST7MDT';
    const TIMEZONE_MEXICOBAJA_NORTE = 'Mexico/BajaNorte';
    const TIMEZONE_MEXICOBAJA_SUR = 'Mexico/BajaSur';
    const TIMEZONE_MEXICOGENERAL = 'Mexico/General';
    const TIMEZONE_NZ = 'NZ';
    const TIMEZONE_NZ_CHAT = 'NZ-CHAT';
    const TIMEZONE_NAVAJO = 'Navajo';
    const TIMEZONE_PRC = 'PRC';
    const TIMEZONE_PST8_PDT = 'PST8PDT';
    const TIMEZONE_PACIFICAPIA = 'Pacific/Apia';
    const TIMEZONE_PACIFICAUCKLAND = 'Pacific/Auckland';
    const TIMEZONE_PACIFICBOUGAINVILLE = 'Pacific/Bougainville';
    const TIMEZONE_PACIFICCHATHAM = 'Pacific/Chatham';
    const TIMEZONE_PACIFICCHUUK = 'Pacific/Chuuk';
    const TIMEZONE_PACIFICEASTER = 'Pacific/Easter';
    const TIMEZONE_PACIFICEFATE = 'Pacific/Efate';
    const TIMEZONE_PACIFICENDERBURY = 'Pacific/Enderbury';
    const TIMEZONE_PACIFICFAKAOFO = 'Pacific/Fakaofo';
    const TIMEZONE_PACIFICFIJI = 'Pacific/Fiji';
    const TIMEZONE_PACIFICFUNAFUTI = 'Pacific/Funafuti';
    const TIMEZONE_PACIFICGALAPAGOS = 'Pacific/Galapagos';
    const TIMEZONE_PACIFICGAMBIER = 'Pacific/Gambier';
    const TIMEZONE_PACIFICGUADALCANAL = 'Pacific/Guadalcanal';
    const TIMEZONE_PACIFICGUAM = 'Pacific/Guam';
    const TIMEZONE_PACIFICHONOLULU = 'Pacific/Honolulu';
    const TIMEZONE_PACIFICJOHNSTON = 'Pacific/Johnston';
    const TIMEZONE_PACIFICKIRITIMATI = 'Pacific/Kiritimati';
    const TIMEZONE_PACIFICKOSRAE = 'Pacific/Kosrae';
    const TIMEZONE_PACIFICKWAJALEIN = 'Pacific/Kwajalein';
    const TIMEZONE_PACIFICMAJURO = 'Pacific/Majuro';
    const TIMEZONE_PACIFICMARQUESAS = 'Pacific/Marquesas';
    const TIMEZONE_PACIFICMIDWAY = 'Pacific/Midway';
    const TIMEZONE_PACIFICNAURU = 'Pacific/Nauru';
    const TIMEZONE_PACIFICNIUE = 'Pacific/Niue';
    const TIMEZONE_PACIFICNORFOLK = 'Pacific/Norfolk';
    const TIMEZONE_PACIFICNOUMEA = 'Pacific/Noumea';
    const TIMEZONE_PACIFICPAGO_PAGO = 'Pacific/Pago_Pago';
    const TIMEZONE_PACIFICPALAU = 'Pacific/Palau';
    const TIMEZONE_PACIFICPITCAIRN = 'Pacific/Pitcairn';
    const TIMEZONE_PACIFICPOHNPEI = 'Pacific/Pohnpei';
    const TIMEZONE_PACIFICPONAPE = 'Pacific/Ponape';
    const TIMEZONE_PACIFICPORT_MORESBY = 'Pacific/Port_Moresby';
    const TIMEZONE_PACIFICRAROTONGA = 'Pacific/Rarotonga';
    const TIMEZONE_PACIFICSAIPAN = 'Pacific/Saipan';
    const TIMEZONE_PACIFICSAMOA = 'Pacific/Samoa';
    const TIMEZONE_PACIFICTAHITI = 'Pacific/Tahiti';
    const TIMEZONE_PACIFICTARAWA = 'Pacific/Tarawa';
    const TIMEZONE_PACIFICTONGATAPU = 'Pacific/Tongatapu';
    const TIMEZONE_PACIFICTRUK = 'Pacific/Truk';
    const TIMEZONE_PACIFICWAKE = 'Pacific/Wake';
    const TIMEZONE_PACIFICWALLIS = 'Pacific/Wallis';
    const TIMEZONE_PACIFICYAP = 'Pacific/Yap';
    const TIMEZONE_POLAND = 'Poland';
    const TIMEZONE_PORTUGAL = 'Portugal';
    const TIMEZONE_ROC = 'ROC';
    const TIMEZONE_ROK = 'ROK';
    const TIMEZONE_SINGAPORE = 'Singapore';
    const TIMEZONE_SYSTEM_VAST4 = 'SystemV/AST4';
    const TIMEZONE_SYSTEM_VAST4_ADT = 'SystemV/AST4ADT';
    const TIMEZONE_SYSTEM_VCST6 = 'SystemV/CST6';
    const TIMEZONE_SYSTEM_VCST6_CDT = 'SystemV/CST6CDT';
    const TIMEZONE_SYSTEM_VEST5 = 'SystemV/EST5';
    const TIMEZONE_SYSTEM_VEST5_EDT = 'SystemV/EST5EDT';
    const TIMEZONE_SYSTEM_VHST10 = 'SystemV/HST10';
    const TIMEZONE_SYSTEM_VMST7 = 'SystemV/MST7';
    const TIMEZONE_SYSTEM_VMST7_MDT = 'SystemV/MST7MDT';
    const TIMEZONE_SYSTEM_VPST8 = 'SystemV/PST8';
    const TIMEZONE_SYSTEM_VPST8_PDT = 'SystemV/PST8PDT';
    const TIMEZONE_SYSTEM_VYST9 = 'SystemV/YST9';
    const TIMEZONE_SYSTEM_VYST9_YDT = 'SystemV/YST9YDT';
    const TIMEZONE_TURKEY = 'Turkey';
    const TIMEZONE_UCT = 'UCT';
    const TIMEZONE_USALASKA = 'US/Alaska';
    const TIMEZONE_USALEUTIAN = 'US/Aleutian';
    const TIMEZONE_USARIZONA = 'US/Arizona';
    const TIMEZONE_USCENTRAL = 'US/Central';
    const TIMEZONE_USEAST_INDIANA = 'US/East-Indiana';
    const TIMEZONE_USEASTERN = 'US/Eastern';
    const TIMEZONE_USHAWAII = 'US/Hawaii';
    const TIMEZONE_USINDIANA_STARKE = 'US/Indiana-Starke';
    const TIMEZONE_USMICHIGAN = 'US/Michigan';
    const TIMEZONE_USMOUNTAIN = 'US/Mountain';
    const TIMEZONE_USPACIFIC = 'US/Pacific';
    const TIMEZONE_USPACIFIC_NEW = 'US/Pacific-New';
    const TIMEZONE_USSAMOA = 'US/Samoa';
    const TIMEZONE_UTC = 'UTC';
    const TIMEZONE_UNIVERSAL = 'Universal';
    const TIMEZONE_W_SU = 'W-SU';
    const TIMEZONE_WET = 'WET';
    const TIMEZONE_ZULU = 'Zulu';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_FAILED_TO_REACH,
            self::STATUS_NO_LONGER_CALL,
            self::STATUS_MAYBE_INTERESTED,
            self::STATUS_READY_FOR_CALL,
            self::STATUS_OUTDATED,
            self::STATUS_VOICEMAIL,
            self::STATUS_DELETED,
            self::STATUS_COMPLETED,
            self::STATUS_FAILED,
            self::STATUS_DNC,
            self::STATUS_INCOMPLETED,
            self::STATUS_UNTRIED,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getUrgencyAllowableValues()
    {
        return [
            self::URGENCY_ASAP,
            self::URGENCY_SAME_DAY,
            self::URGENCY_SAME_WEEK,
            self::URGENCY_SAME_MONTH,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getTimezoneAllowableValues()
    {
        return [
            self::TIMEZONE_AFRICAABIDJAN,
            self::TIMEZONE_AFRICAACCRA,
            self::TIMEZONE_AFRICAADDIS_ABABA,
            self::TIMEZONE_AFRICAALGIERS,
            self::TIMEZONE_AFRICAASMARA,
            self::TIMEZONE_AFRICAASMERA,
            self::TIMEZONE_AFRICABAMAKO,
            self::TIMEZONE_AFRICABANGUI,
            self::TIMEZONE_AFRICABANJUL,
            self::TIMEZONE_AFRICABISSAU,
            self::TIMEZONE_AFRICABLANTYRE,
            self::TIMEZONE_AFRICABRAZZAVILLE,
            self::TIMEZONE_AFRICABUJUMBURA,
            self::TIMEZONE_AFRICACAIRO,
            self::TIMEZONE_AFRICACASABLANCA,
            self::TIMEZONE_AFRICACEUTA,
            self::TIMEZONE_AFRICACONAKRY,
            self::TIMEZONE_AFRICADAKAR,
            self::TIMEZONE_AFRICADAR_ES_SALAAM,
            self::TIMEZONE_AFRICADJIBOUTI,
            self::TIMEZONE_AFRICADOUALA,
            self::TIMEZONE_AFRICAEL_AAIUN,
            self::TIMEZONE_AFRICAFREETOWN,
            self::TIMEZONE_AFRICAGABORONE,
            self::TIMEZONE_AFRICAHARARE,
            self::TIMEZONE_AFRICAJOHANNESBURG,
            self::TIMEZONE_AFRICAJUBA,
            self::TIMEZONE_AFRICAKAMPALA,
            self::TIMEZONE_AFRICAKHARTOUM,
            self::TIMEZONE_AFRICAKIGALI,
            self::TIMEZONE_AFRICAKINSHASA,
            self::TIMEZONE_AFRICALAGOS,
            self::TIMEZONE_AFRICALIBREVILLE,
            self::TIMEZONE_AFRICALOME,
            self::TIMEZONE_AFRICALUANDA,
            self::TIMEZONE_AFRICALUBUMBASHI,
            self::TIMEZONE_AFRICALUSAKA,
            self::TIMEZONE_AFRICAMALABO,
            self::TIMEZONE_AFRICAMAPUTO,
            self::TIMEZONE_AFRICAMASERU,
            self::TIMEZONE_AFRICAMBABANE,
            self::TIMEZONE_AFRICAMOGADISHU,
            self::TIMEZONE_AFRICAMONROVIA,
            self::TIMEZONE_AFRICANAIROBI,
            self::TIMEZONE_AFRICANDJAMENA,
            self::TIMEZONE_AFRICANIAMEY,
            self::TIMEZONE_AFRICANOUAKCHOTT,
            self::TIMEZONE_AFRICAOUAGADOUGOU,
            self::TIMEZONE_AFRICAPORTO_NOVO,
            self::TIMEZONE_AFRICASAO_TOME,
            self::TIMEZONE_AFRICATIMBUKTU,
            self::TIMEZONE_AFRICATRIPOLI,
            self::TIMEZONE_AFRICATUNIS,
            self::TIMEZONE_AFRICAWINDHOEK,
            self::TIMEZONE_AMERICAADAK,
            self::TIMEZONE_AMERICAANCHORAGE,
            self::TIMEZONE_AMERICAANGUILLA,
            self::TIMEZONE_AMERICAANTIGUA,
            self::TIMEZONE_AMERICAARAGUAINA,
            self::TIMEZONE_AMERICAARGENTINABUENOS_AIRES,
            self::TIMEZONE_AMERICAARGENTINACATAMARCA,
            self::TIMEZONE_AMERICAARGENTINACOMOD_RIVADAVIA,
            self::TIMEZONE_AMERICAARGENTINACORDOBA,
            self::TIMEZONE_AMERICAARGENTINAJUJUY,
            self::TIMEZONE_AMERICAARGENTINALA_RIOJA,
            self::TIMEZONE_AMERICAARGENTINAMENDOZA,
            self::TIMEZONE_AMERICAARGENTINARIO_GALLEGOS,
            self::TIMEZONE_AMERICAARGENTINASALTA,
            self::TIMEZONE_AMERICAARGENTINASAN_JUAN,
            self::TIMEZONE_AMERICAARGENTINASAN_LUIS,
            self::TIMEZONE_AMERICAARGENTINATUCUMAN,
            self::TIMEZONE_AMERICAARGENTINAUSHUAIA,
            self::TIMEZONE_AMERICAARUBA,
            self::TIMEZONE_AMERICAASUNCION,
            self::TIMEZONE_AMERICAATIKOKAN,
            self::TIMEZONE_AMERICAATKA,
            self::TIMEZONE_AMERICABAHIA,
            self::TIMEZONE_AMERICABAHIA_BANDERAS,
            self::TIMEZONE_AMERICABARBADOS,
            self::TIMEZONE_AMERICABELEM,
            self::TIMEZONE_AMERICABELIZE,
            self::TIMEZONE_AMERICABLANC_SABLON,
            self::TIMEZONE_AMERICABOA_VISTA,
            self::TIMEZONE_AMERICABOGOTA,
            self::TIMEZONE_AMERICABOISE,
            self::TIMEZONE_AMERICABUENOS_AIRES,
            self::TIMEZONE_AMERICACAMBRIDGE_BAY,
            self::TIMEZONE_AMERICACAMPO_GRANDE,
            self::TIMEZONE_AMERICACANCUN,
            self::TIMEZONE_AMERICACARACAS,
            self::TIMEZONE_AMERICACATAMARCA,
            self::TIMEZONE_AMERICACAYENNE,
            self::TIMEZONE_AMERICACAYMAN,
            self::TIMEZONE_AMERICACHICAGO,
            self::TIMEZONE_AMERICACHIHUAHUA,
            self::TIMEZONE_AMERICACORAL_HARBOUR,
            self::TIMEZONE_AMERICACORDOBA,
            self::TIMEZONE_AMERICACOSTA_RICA,
            self::TIMEZONE_AMERICACRESTON,
            self::TIMEZONE_AMERICACUIABA,
            self::TIMEZONE_AMERICACURACAO,
            self::TIMEZONE_AMERICADANMARKSHAVN,
            self::TIMEZONE_AMERICADAWSON,
            self::TIMEZONE_AMERICADAWSON_CREEK,
            self::TIMEZONE_AMERICADENVER,
            self::TIMEZONE_AMERICADETROIT,
            self::TIMEZONE_AMERICADOMINICA,
            self::TIMEZONE_AMERICAEDMONTON,
            self::TIMEZONE_AMERICAEIRUNEPE,
            self::TIMEZONE_AMERICAEL_SALVADOR,
            self::TIMEZONE_AMERICAENSENADA,
            self::TIMEZONE_AMERICAFORT_NELSON,
            self::TIMEZONE_AMERICAFORT_WAYNE,
            self::TIMEZONE_AMERICAFORTALEZA,
            self::TIMEZONE_AMERICAGLACE_BAY,
            self::TIMEZONE_AMERICAGODTHAB,
            self::TIMEZONE_AMERICAGOOSE_BAY,
            self::TIMEZONE_AMERICAGRAND_TURK,
            self::TIMEZONE_AMERICAGRENADA,
            self::TIMEZONE_AMERICAGUADELOUPE,
            self::TIMEZONE_AMERICAGUATEMALA,
            self::TIMEZONE_AMERICAGUAYAQUIL,
            self::TIMEZONE_AMERICAGUYANA,
            self::TIMEZONE_AMERICAHALIFAX,
            self::TIMEZONE_AMERICAHAVANA,
            self::TIMEZONE_AMERICAHERMOSILLO,
            self::TIMEZONE_AMERICAINDIANAINDIANAPOLIS,
            self::TIMEZONE_AMERICAINDIANAKNOX,
            self::TIMEZONE_AMERICAINDIANAMARENGO,
            self::TIMEZONE_AMERICAINDIANAPETERSBURG,
            self::TIMEZONE_AMERICAINDIANATELL_CITY,
            self::TIMEZONE_AMERICAINDIANAVEVAY,
            self::TIMEZONE_AMERICAINDIANAVINCENNES,
            self::TIMEZONE_AMERICAINDIANAWINAMAC,
            self::TIMEZONE_AMERICAINDIANAPOLIS,
            self::TIMEZONE_AMERICAINUVIK,
            self::TIMEZONE_AMERICAIQALUIT,
            self::TIMEZONE_AMERICAJAMAICA,
            self::TIMEZONE_AMERICAJUJUY,
            self::TIMEZONE_AMERICAJUNEAU,
            self::TIMEZONE_AMERICAKENTUCKYLOUISVILLE,
            self::TIMEZONE_AMERICAKENTUCKYMONTICELLO,
            self::TIMEZONE_AMERICAKNOX_IN,
            self::TIMEZONE_AMERICAKRALENDIJK,
            self::TIMEZONE_AMERICALA_PAZ,
            self::TIMEZONE_AMERICALIMA,
            self::TIMEZONE_AMERICALOS_ANGELES,
            self::TIMEZONE_AMERICALOUISVILLE,
            self::TIMEZONE_AMERICALOWER_PRINCES,
            self::TIMEZONE_AMERICAMACEIO,
            self::TIMEZONE_AMERICAMANAGUA,
            self::TIMEZONE_AMERICAMANAUS,
            self::TIMEZONE_AMERICAMARIGOT,
            self::TIMEZONE_AMERICAMARTINIQUE,
            self::TIMEZONE_AMERICAMATAMOROS,
            self::TIMEZONE_AMERICAMAZATLAN,
            self::TIMEZONE_AMERICAMENDOZA,
            self::TIMEZONE_AMERICAMENOMINEE,
            self::TIMEZONE_AMERICAMERIDA,
            self::TIMEZONE_AMERICAMETLAKATLA,
            self::TIMEZONE_AMERICAMEXICO_CITY,
            self::TIMEZONE_AMERICAMIQUELON,
            self::TIMEZONE_AMERICAMONCTON,
            self::TIMEZONE_AMERICAMONTERREY,
            self::TIMEZONE_AMERICAMONTEVIDEO,
            self::TIMEZONE_AMERICAMONTREAL,
            self::TIMEZONE_AMERICAMONTSERRAT,
            self::TIMEZONE_AMERICANASSAU,
            self::TIMEZONE_AMERICANEW_YORK,
            self::TIMEZONE_AMERICANIPIGON,
            self::TIMEZONE_AMERICANOME,
            self::TIMEZONE_AMERICANORONHA,
            self::TIMEZONE_AMERICANORTH_DAKOTABEULAH,
            self::TIMEZONE_AMERICANORTH_DAKOTACENTER,
            self::TIMEZONE_AMERICANORTH_DAKOTANEW_SALEM,
            self::TIMEZONE_AMERICAOJINAGA,
            self::TIMEZONE_AMERICAPANAMA,
            self::TIMEZONE_AMERICAPANGNIRTUNG,
            self::TIMEZONE_AMERICAPARAMARIBO,
            self::TIMEZONE_AMERICAPHOENIX,
            self::TIMEZONE_AMERICAPORT_AU_PRINCE,
            self::TIMEZONE_AMERICAPORT_OF_SPAIN,
            self::TIMEZONE_AMERICAPORTO_ACRE,
            self::TIMEZONE_AMERICAPORTO_VELHO,
            self::TIMEZONE_AMERICAPUERTO_RICO,
            self::TIMEZONE_AMERICAPUNTA_ARENAS,
            self::TIMEZONE_AMERICARAINY_RIVER,
            self::TIMEZONE_AMERICARANKIN_INLET,
            self::TIMEZONE_AMERICARECIFE,
            self::TIMEZONE_AMERICAREGINA,
            self::TIMEZONE_AMERICARESOLUTE,
            self::TIMEZONE_AMERICARIO_BRANCO,
            self::TIMEZONE_AMERICAROSARIO,
            self::TIMEZONE_AMERICASANTA_ISABEL,
            self::TIMEZONE_AMERICASANTAREM,
            self::TIMEZONE_AMERICASANTIAGO,
            self::TIMEZONE_AMERICASANTO_DOMINGO,
            self::TIMEZONE_AMERICASAO_PAULO,
            self::TIMEZONE_AMERICASCORESBYSUND,
            self::TIMEZONE_AMERICASHIPROCK,
            self::TIMEZONE_AMERICASITKA,
            self::TIMEZONE_AMERICAST_BARTHELEMY,
            self::TIMEZONE_AMERICAST_JOHNS,
            self::TIMEZONE_AMERICAST_KITTS,
            self::TIMEZONE_AMERICAST_LUCIA,
            self::TIMEZONE_AMERICAST_THOMAS,
            self::TIMEZONE_AMERICAST_VINCENT,
            self::TIMEZONE_AMERICASWIFT_CURRENT,
            self::TIMEZONE_AMERICATEGUCIGALPA,
            self::TIMEZONE_AMERICATHULE,
            self::TIMEZONE_AMERICATHUNDER_BAY,
            self::TIMEZONE_AMERICATIJUANA,
            self::TIMEZONE_AMERICATORONTO,
            self::TIMEZONE_AMERICATORTOLA,
            self::TIMEZONE_AMERICAVANCOUVER,
            self::TIMEZONE_AMERICAVIRGIN,
            self::TIMEZONE_AMERICAWHITEHORSE,
            self::TIMEZONE_AMERICAWINNIPEG,
            self::TIMEZONE_AMERICAYAKUTAT,
            self::TIMEZONE_AMERICAYELLOWKNIFE,
            self::TIMEZONE_ANTARCTICACASEY,
            self::TIMEZONE_ANTARCTICADAVIS,
            self::TIMEZONE_ANTARCTICADUMONT_D_URVILLE,
            self::TIMEZONE_ANTARCTICAMACQUARIE,
            self::TIMEZONE_ANTARCTICAMAWSON,
            self::TIMEZONE_ANTARCTICAMC_MURDO,
            self::TIMEZONE_ANTARCTICAPALMER,
            self::TIMEZONE_ANTARCTICAROTHERA,
            self::TIMEZONE_ANTARCTICASOUTH_POLE,
            self::TIMEZONE_ANTARCTICASYOWA,
            self::TIMEZONE_ANTARCTICATROLL,
            self::TIMEZONE_ANTARCTICAVOSTOK,
            self::TIMEZONE_ARCTICLONGYEARBYEN,
            self::TIMEZONE_ASIAADEN,
            self::TIMEZONE_ASIAALMATY,
            self::TIMEZONE_ASIAAMMAN,
            self::TIMEZONE_ASIAANADYR,
            self::TIMEZONE_ASIAAQTAU,
            self::TIMEZONE_ASIAAQTOBE,
            self::TIMEZONE_ASIAASHGABAT,
            self::TIMEZONE_ASIAASHKHABAD,
            self::TIMEZONE_ASIAATYRAU,
            self::TIMEZONE_ASIABAGHDAD,
            self::TIMEZONE_ASIABAHRAIN,
            self::TIMEZONE_ASIABAKU,
            self::TIMEZONE_ASIABANGKOK,
            self::TIMEZONE_ASIABARNAUL,
            self::TIMEZONE_ASIABEIRUT,
            self::TIMEZONE_ASIABISHKEK,
            self::TIMEZONE_ASIABRUNEI,
            self::TIMEZONE_ASIACALCUTTA,
            self::TIMEZONE_ASIACHITA,
            self::TIMEZONE_ASIACHOIBALSAN,
            self::TIMEZONE_ASIACHONGQING,
            self::TIMEZONE_ASIACHUNGKING,
            self::TIMEZONE_ASIACOLOMBO,
            self::TIMEZONE_ASIADACCA,
            self::TIMEZONE_ASIADAMASCUS,
            self::TIMEZONE_ASIADHAKA,
            self::TIMEZONE_ASIADILI,
            self::TIMEZONE_ASIADUBAI,
            self::TIMEZONE_ASIADUSHANBE,
            self::TIMEZONE_ASIAFAMAGUSTA,
            self::TIMEZONE_ASIAGAZA,
            self::TIMEZONE_ASIAHARBIN,
            self::TIMEZONE_ASIAHEBRON,
            self::TIMEZONE_ASIAHO_CHI_MINH,
            self::TIMEZONE_ASIAHONG_KONG,
            self::TIMEZONE_ASIAHOVD,
            self::TIMEZONE_ASIAIRKUTSK,
            self::TIMEZONE_ASIAISTANBUL,
            self::TIMEZONE_ASIAJAKARTA,
            self::TIMEZONE_ASIAJAYAPURA,
            self::TIMEZONE_ASIAJERUSALEM,
            self::TIMEZONE_ASIAKABUL,
            self::TIMEZONE_ASIAKAMCHATKA,
            self::TIMEZONE_ASIAKARACHI,
            self::TIMEZONE_ASIAKASHGAR,
            self::TIMEZONE_ASIAKATHMANDU,
            self::TIMEZONE_ASIAKATMANDU,
            self::TIMEZONE_ASIAKHANDYGA,
            self::TIMEZONE_ASIAKOLKATA,
            self::TIMEZONE_ASIAKRASNOYARSK,
            self::TIMEZONE_ASIAKUALA_LUMPUR,
            self::TIMEZONE_ASIAKUCHING,
            self::TIMEZONE_ASIAKUWAIT,
            self::TIMEZONE_ASIAMACAO,
            self::TIMEZONE_ASIAMACAU,
            self::TIMEZONE_ASIAMAGADAN,
            self::TIMEZONE_ASIAMAKASSAR,
            self::TIMEZONE_ASIAMANILA,
            self::TIMEZONE_ASIAMUSCAT,
            self::TIMEZONE_ASIANICOSIA,
            self::TIMEZONE_ASIANOVOKUZNETSK,
            self::TIMEZONE_ASIANOVOSIBIRSK,
            self::TIMEZONE_ASIAOMSK,
            self::TIMEZONE_ASIAORAL,
            self::TIMEZONE_ASIAPHNOM_PENH,
            self::TIMEZONE_ASIAPONTIANAK,
            self::TIMEZONE_ASIAPYONGYANG,
            self::TIMEZONE_ASIAQATAR,
            self::TIMEZONE_ASIAQYZYLORDA,
            self::TIMEZONE_ASIARANGOON,
            self::TIMEZONE_ASIARIYADH,
            self::TIMEZONE_ASIASAIGON,
            self::TIMEZONE_ASIASAKHALIN,
            self::TIMEZONE_ASIASAMARKAND,
            self::TIMEZONE_ASIASEOUL,
            self::TIMEZONE_ASIASHANGHAI,
            self::TIMEZONE_ASIASINGAPORE,
            self::TIMEZONE_ASIASREDNEKOLYMSK,
            self::TIMEZONE_ASIATAIPEI,
            self::TIMEZONE_ASIATASHKENT,
            self::TIMEZONE_ASIATBILISI,
            self::TIMEZONE_ASIATEHRAN,
            self::TIMEZONE_ASIATEL_AVIV,
            self::TIMEZONE_ASIATHIMBU,
            self::TIMEZONE_ASIATHIMPHU,
            self::TIMEZONE_ASIATOKYO,
            self::TIMEZONE_ASIATOMSK,
            self::TIMEZONE_ASIAUJUNG_PANDANG,
            self::TIMEZONE_ASIAULAANBAATAR,
            self::TIMEZONE_ASIAULAN_BATOR,
            self::TIMEZONE_ASIAURUMQI,
            self::TIMEZONE_ASIAUST_NERA,
            self::TIMEZONE_ASIAVIENTIANE,
            self::TIMEZONE_ASIAVLADIVOSTOK,
            self::TIMEZONE_ASIAYAKUTSK,
            self::TIMEZONE_ASIAYANGON,
            self::TIMEZONE_ASIAYEKATERINBURG,
            self::TIMEZONE_ASIAYEREVAN,
            self::TIMEZONE_ATLANTICAZORES,
            self::TIMEZONE_ATLANTICBERMUDA,
            self::TIMEZONE_ATLANTICCANARY,
            self::TIMEZONE_ATLANTICCAPE_VERDE,
            self::TIMEZONE_ATLANTICFAEROE,
            self::TIMEZONE_ATLANTICFAROE,
            self::TIMEZONE_ATLANTICJAN_MAYEN,
            self::TIMEZONE_ATLANTICMADEIRA,
            self::TIMEZONE_ATLANTICREYKJAVIK,
            self::TIMEZONE_ATLANTICSOUTH_GEORGIA,
            self::TIMEZONE_ATLANTICST_HELENA,
            self::TIMEZONE_ATLANTICSTANLEY,
            self::TIMEZONE_AUSTRALIAACT,
            self::TIMEZONE_AUSTRALIAADELAIDE,
            self::TIMEZONE_AUSTRALIABRISBANE,
            self::TIMEZONE_AUSTRALIABROKEN_HILL,
            self::TIMEZONE_AUSTRALIACANBERRA,
            self::TIMEZONE_AUSTRALIACURRIE,
            self::TIMEZONE_AUSTRALIADARWIN,
            self::TIMEZONE_AUSTRALIAEUCLA,
            self::TIMEZONE_AUSTRALIAHOBART,
            self::TIMEZONE_AUSTRALIALHI,
            self::TIMEZONE_AUSTRALIALINDEMAN,
            self::TIMEZONE_AUSTRALIALORD_HOWE,
            self::TIMEZONE_AUSTRALIAMELBOURNE,
            self::TIMEZONE_AUSTRALIANSW,
            self::TIMEZONE_AUSTRALIANORTH,
            self::TIMEZONE_AUSTRALIAPERTH,
            self::TIMEZONE_AUSTRALIAQUEENSLAND,
            self::TIMEZONE_AUSTRALIASOUTH,
            self::TIMEZONE_AUSTRALIASYDNEY,
            self::TIMEZONE_AUSTRALIATASMANIA,
            self::TIMEZONE_AUSTRALIAVICTORIA,
            self::TIMEZONE_AUSTRALIAWEST,
            self::TIMEZONE_AUSTRALIAYANCOWINNA,
            self::TIMEZONE_BRAZILACRE,
            self::TIMEZONE_BRAZILDE_NORONHA,
            self::TIMEZONE_BRAZILEAST,
            self::TIMEZONE_BRAZILWEST,
            self::TIMEZONE_CET,
            self::TIMEZONE_CST6_CDT,
            self::TIMEZONE_CANADAATLANTIC,
            self::TIMEZONE_CANADACENTRAL,
            self::TIMEZONE_CANADAEASTERN,
            self::TIMEZONE_CANADAMOUNTAIN,
            self::TIMEZONE_CANADANEWFOUNDLAND,
            self::TIMEZONE_CANADAPACIFIC,
            self::TIMEZONE_CANADASASKATCHEWAN,
            self::TIMEZONE_CANADAYUKON,
            self::TIMEZONE_CHILECONTINENTAL,
            self::TIMEZONE_CHILEEASTER_ISLAND,
            self::TIMEZONE_CUBA,
            self::TIMEZONE_EET,
            self::TIMEZONE_EST,
            self::TIMEZONE_EST5_EDT,
            self::TIMEZONE_EGYPT,
            self::TIMEZONE_EIRE,
            self::TIMEZONE_ETCGMT,
            self::TIMEZONE_ETCGMT0,
            self::TIMEZONE_ETCGMT1,
            self::TIMEZONE_ETCGMT10,
            self::TIMEZONE_ETCGMT11,
            self::TIMEZONE_ETCGMT12,
            self::TIMEZONE_ETCGMT2,
            self::TIMEZONE_ETCGMT3,
            self::TIMEZONE_ETCGMT4,
            self::TIMEZONE_ETCGMT5,
            self::TIMEZONE_ETCGMT6,
            self::TIMEZONE_ETCGMT7,
            self::TIMEZONE_ETCGMT8,
            self::TIMEZONE_ETCGMT9,
            self::TIMEZONE_ETCGMT_0,
            self::TIMEZONE_ETCGMT_1,
            self::TIMEZONE_ETCGMT_10,
            self::TIMEZONE_ETCGMT_11,
            self::TIMEZONE_ETCGMT_12,
            self::TIMEZONE_ETCGMT_13,
            self::TIMEZONE_ETCGMT_14,
            self::TIMEZONE_ETCGMT_2,
            self::TIMEZONE_ETCGMT_3,
            self::TIMEZONE_ETCGMT_4,
            self::TIMEZONE_ETCGMT_5,
            self::TIMEZONE_ETCGMT_6,
            self::TIMEZONE_ETCGMT_7,
            self::TIMEZONE_ETCGMT_8,
            self::TIMEZONE_ETCGMT_9,
            self::TIMEZONE_ETCGMT0,
            self::TIMEZONE_ETCGREENWICH,
            self::TIMEZONE_ETCUCT,
            self::TIMEZONE_ETCUTC,
            self::TIMEZONE_ETCUNIVERSAL,
            self::TIMEZONE_ETCZULU,
            self::TIMEZONE_EUROPEAMSTERDAM,
            self::TIMEZONE_EUROPEANDORRA,
            self::TIMEZONE_EUROPEASTRAKHAN,
            self::TIMEZONE_EUROPEATHENS,
            self::TIMEZONE_EUROPEBELFAST,
            self::TIMEZONE_EUROPEBELGRADE,
            self::TIMEZONE_EUROPEBERLIN,
            self::TIMEZONE_EUROPEBRATISLAVA,
            self::TIMEZONE_EUROPEBRUSSELS,
            self::TIMEZONE_EUROPEBUCHAREST,
            self::TIMEZONE_EUROPEBUDAPEST,
            self::TIMEZONE_EUROPEBUSINGEN,
            self::TIMEZONE_EUROPECHISINAU,
            self::TIMEZONE_EUROPECOPENHAGEN,
            self::TIMEZONE_EUROPEDUBLIN,
            self::TIMEZONE_EUROPEGIBRALTAR,
            self::TIMEZONE_EUROPEGUERNSEY,
            self::TIMEZONE_EUROPEHELSINKI,
            self::TIMEZONE_EUROPEISLE_OF_MAN,
            self::TIMEZONE_EUROPEISTANBUL,
            self::TIMEZONE_EUROPEJERSEY,
            self::TIMEZONE_EUROPEKALININGRAD,
            self::TIMEZONE_EUROPEKIEV,
            self::TIMEZONE_EUROPEKIROV,
            self::TIMEZONE_EUROPELISBON,
            self::TIMEZONE_EUROPELJUBLJANA,
            self::TIMEZONE_EUROPELONDON,
            self::TIMEZONE_EUROPELUXEMBOURG,
            self::TIMEZONE_EUROPEMADRID,
            self::TIMEZONE_EUROPEMALTA,
            self::TIMEZONE_EUROPEMARIEHAMN,
            self::TIMEZONE_EUROPEMINSK,
            self::TIMEZONE_EUROPEMONACO,
            self::TIMEZONE_EUROPEMOSCOW,
            self::TIMEZONE_EUROPENICOSIA,
            self::TIMEZONE_EUROPEOSLO,
            self::TIMEZONE_EUROPEPARIS,
            self::TIMEZONE_EUROPEPODGORICA,
            self::TIMEZONE_EUROPEPRAGUE,
            self::TIMEZONE_EUROPERIGA,
            self::TIMEZONE_EUROPEROME,
            self::TIMEZONE_EUROPESAMARA,
            self::TIMEZONE_EUROPESAN_MARINO,
            self::TIMEZONE_EUROPESARAJEVO,
            self::TIMEZONE_EUROPESARATOV,
            self::TIMEZONE_EUROPESIMFEROPOL,
            self::TIMEZONE_EUROPESKOPJE,
            self::TIMEZONE_EUROPESOFIA,
            self::TIMEZONE_EUROPESTOCKHOLM,
            self::TIMEZONE_EUROPETALLINN,
            self::TIMEZONE_EUROPETIRANE,
            self::TIMEZONE_EUROPETIRASPOL,
            self::TIMEZONE_EUROPEULYANOVSK,
            self::TIMEZONE_EUROPEUZHGOROD,
            self::TIMEZONE_EUROPEVADUZ,
            self::TIMEZONE_EUROPEVATICAN,
            self::TIMEZONE_EUROPEVIENNA,
            self::TIMEZONE_EUROPEVILNIUS,
            self::TIMEZONE_EUROPEVOLGOGRAD,
            self::TIMEZONE_EUROPEWARSAW,
            self::TIMEZONE_EUROPEZAGREB,
            self::TIMEZONE_EUROPEZAPOROZHYE,
            self::TIMEZONE_EUROPEZURICH,
            self::TIMEZONE_FACTORY,
            self::TIMEZONE_GB,
            self::TIMEZONE_GB_EIRE,
            self::TIMEZONE_GMT,
            self::TIMEZONE_GMT0,
            self::TIMEZONE_GMT_0,
            self::TIMEZONE_GMT0,
            self::TIMEZONE_GREENWICH,
            self::TIMEZONE_HST,
            self::TIMEZONE_HONGKONG,
            self::TIMEZONE_ICELAND,
            self::TIMEZONE_INDIANANTANANARIVO,
            self::TIMEZONE_INDIANCHAGOS,
            self::TIMEZONE_INDIANCHRISTMAS,
            self::TIMEZONE_INDIANCOCOS,
            self::TIMEZONE_INDIANCOMORO,
            self::TIMEZONE_INDIANKERGUELEN,
            self::TIMEZONE_INDIANMAHE,
            self::TIMEZONE_INDIANMALDIVES,
            self::TIMEZONE_INDIANMAURITIUS,
            self::TIMEZONE_INDIANMAYOTTE,
            self::TIMEZONE_INDIANREUNION,
            self::TIMEZONE_IRAN,
            self::TIMEZONE_ISRAEL,
            self::TIMEZONE_JAMAICA,
            self::TIMEZONE_JAPAN,
            self::TIMEZONE_KWAJALEIN,
            self::TIMEZONE_LIBYA,
            self::TIMEZONE_MET,
            self::TIMEZONE_MST,
            self::TIMEZONE_MST7_MDT,
            self::TIMEZONE_MEXICOBAJA_NORTE,
            self::TIMEZONE_MEXICOBAJA_SUR,
            self::TIMEZONE_MEXICOGENERAL,
            self::TIMEZONE_NZ,
            self::TIMEZONE_NZ_CHAT,
            self::TIMEZONE_NAVAJO,
            self::TIMEZONE_PRC,
            self::TIMEZONE_PST8_PDT,
            self::TIMEZONE_PACIFICAPIA,
            self::TIMEZONE_PACIFICAUCKLAND,
            self::TIMEZONE_PACIFICBOUGAINVILLE,
            self::TIMEZONE_PACIFICCHATHAM,
            self::TIMEZONE_PACIFICCHUUK,
            self::TIMEZONE_PACIFICEASTER,
            self::TIMEZONE_PACIFICEFATE,
            self::TIMEZONE_PACIFICENDERBURY,
            self::TIMEZONE_PACIFICFAKAOFO,
            self::TIMEZONE_PACIFICFIJI,
            self::TIMEZONE_PACIFICFUNAFUTI,
            self::TIMEZONE_PACIFICGALAPAGOS,
            self::TIMEZONE_PACIFICGAMBIER,
            self::TIMEZONE_PACIFICGUADALCANAL,
            self::TIMEZONE_PACIFICGUAM,
            self::TIMEZONE_PACIFICHONOLULU,
            self::TIMEZONE_PACIFICJOHNSTON,
            self::TIMEZONE_PACIFICKIRITIMATI,
            self::TIMEZONE_PACIFICKOSRAE,
            self::TIMEZONE_PACIFICKWAJALEIN,
            self::TIMEZONE_PACIFICMAJURO,
            self::TIMEZONE_PACIFICMARQUESAS,
            self::TIMEZONE_PACIFICMIDWAY,
            self::TIMEZONE_PACIFICNAURU,
            self::TIMEZONE_PACIFICNIUE,
            self::TIMEZONE_PACIFICNORFOLK,
            self::TIMEZONE_PACIFICNOUMEA,
            self::TIMEZONE_PACIFICPAGO_PAGO,
            self::TIMEZONE_PACIFICPALAU,
            self::TIMEZONE_PACIFICPITCAIRN,
            self::TIMEZONE_PACIFICPOHNPEI,
            self::TIMEZONE_PACIFICPONAPE,
            self::TIMEZONE_PACIFICPORT_MORESBY,
            self::TIMEZONE_PACIFICRAROTONGA,
            self::TIMEZONE_PACIFICSAIPAN,
            self::TIMEZONE_PACIFICSAMOA,
            self::TIMEZONE_PACIFICTAHITI,
            self::TIMEZONE_PACIFICTARAWA,
            self::TIMEZONE_PACIFICTONGATAPU,
            self::TIMEZONE_PACIFICTRUK,
            self::TIMEZONE_PACIFICWAKE,
            self::TIMEZONE_PACIFICWALLIS,
            self::TIMEZONE_PACIFICYAP,
            self::TIMEZONE_POLAND,
            self::TIMEZONE_PORTUGAL,
            self::TIMEZONE_ROC,
            self::TIMEZONE_ROK,
            self::TIMEZONE_SINGAPORE,
            self::TIMEZONE_SYSTEM_VAST4,
            self::TIMEZONE_SYSTEM_VAST4_ADT,
            self::TIMEZONE_SYSTEM_VCST6,
            self::TIMEZONE_SYSTEM_VCST6_CDT,
            self::TIMEZONE_SYSTEM_VEST5,
            self::TIMEZONE_SYSTEM_VEST5_EDT,
            self::TIMEZONE_SYSTEM_VHST10,
            self::TIMEZONE_SYSTEM_VMST7,
            self::TIMEZONE_SYSTEM_VMST7_MDT,
            self::TIMEZONE_SYSTEM_VPST8,
            self::TIMEZONE_SYSTEM_VPST8_PDT,
            self::TIMEZONE_SYSTEM_VYST9,
            self::TIMEZONE_SYSTEM_VYST9_YDT,
            self::TIMEZONE_TURKEY,
            self::TIMEZONE_UCT,
            self::TIMEZONE_USALASKA,
            self::TIMEZONE_USALEUTIAN,
            self::TIMEZONE_USARIZONA,
            self::TIMEZONE_USCENTRAL,
            self::TIMEZONE_USEAST_INDIANA,
            self::TIMEZONE_USEASTERN,
            self::TIMEZONE_USHAWAII,
            self::TIMEZONE_USINDIANA_STARKE,
            self::TIMEZONE_USMICHIGAN,
            self::TIMEZONE_USMOUNTAIN,
            self::TIMEZONE_USPACIFIC,
            self::TIMEZONE_USPACIFIC_NEW,
            self::TIMEZONE_USSAMOA,
            self::TIMEZONE_UTC,
            self::TIMEZONE_UNIVERSAL,
            self::TIMEZONE_W_SU,
            self::TIMEZONE_WET,
            self::TIMEZONE_ZULU,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['first_name'] = isset($data['first_name']) ? $data['first_name'] : null;
        $this->container['last_name'] = isset($data['last_name']) ? $data['last_name'] : null;
        $this->container['notes'] = isset($data['notes']) ? $data['notes'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['urgency'] = isset($data['urgency']) ? $data['urgency'] : null;
        $this->container['company'] = isset($data['company']) ? $data['company'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['created_at'] = isset($data['created_at']) ? $data['created_at'] : null;
        $this->container['updated_at'] = isset($data['updated_at']) ? $data['updated_at'] : null;
        $this->container['deleted_at'] = isset($data['deleted_at']) ? $data['deleted_at'] : null;
        $this->container['timezone'] = isset($data['timezone']) ? $data['timezone'] : null;
        $this->container['number'] = isset($data['number']) ? $data['number'] : null;
        $this->container['extension'] = isset($data['extension']) ? $data['extension'] : null;
        $this->container['website'] = isset($data['website']) ? $data['website'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['id'] === null) {
            $invalid_properties[] = "'id' can't be null";
        }
        $allowed_values = $this->getStatusAllowableValues();
        if (!in_array($this->container['status'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'status', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getUrgencyAllowableValues();
        if (!in_array($this->container['urgency'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'urgency', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        $allowed_values = $this->getTimezoneAllowableValues();
        if (!in_array($this->container['timezone'], $allowed_values)) {
            $invalid_properties[] = sprintf(
                "invalid value for 'timezone', must be one of '%s'",
                implode("', '", $allowed_values)
            );
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['id'] === null) {
            return false;
        }
        $allowed_values = $this->getStatusAllowableValues();
        if (!in_array($this->container['status'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getUrgencyAllowableValues();
        if (!in_array($this->container['urgency'], $allowed_values)) {
            return false;
        }
        $allowed_values = $this->getTimezoneAllowableValues();
        if (!in_array($this->container['timezone'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets status
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     * @param string $status Contact status in the system. Allowed statuses for update: dnc, no_longer_call.
     * @return $this
     */
    public function setStatus($status)
    {
        $allowed_values = $this->getStatusAllowableValues();
        if (!is_null($status) && !in_array($status, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'status', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets first_name
     * @return string
     */
    public function getFirstName()
    {
        return $this->container['first_name'];
    }

    /**
     * Sets first_name
     * @param string $first_name Contact's first name
     * @return $this
     */
    public function setFirstName($first_name)
    {
        $this->container['first_name'] = $first_name;

        return $this;
    }

    /**
     * Gets last_name
     * @return string
     */
    public function getLastName()
    {
        return $this->container['last_name'];
    }

    /**
     * Sets last_name
     * @param string $last_name Contact's last name
     * @return $this
     */
    public function setLastName($last_name)
    {
        $this->container['last_name'] = $last_name;

        return $this;
    }

    /**
     * Gets notes
     * @return string
     */
    public function getNotes()
    {
        return $this->container['notes'];
    }

    /**
     * Sets notes
     * @param string $notes Additional notes about the contact
     * @return $this
     */
    public function setNotes($notes)
    {
        $this->container['notes'] = $notes;

        return $this;
    }

    /**
     * Gets title
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     * @param string $title Contact's title at company
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets urgency
     * @return string
     */
    public function getUrgency()
    {
        return $this->container['urgency'];
    }

    /**
     * Sets urgency
     * @param string $urgency
     * @return $this
     */
    public function setUrgency($urgency)
    {
        $allowed_values = $this->getUrgencyAllowableValues();
        if (!is_null($urgency) && !in_array($urgency, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'urgency', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['urgency'] = $urgency;

        return $this;
    }

    /**
     * Gets company
     * @return string
     */
    public function getCompany()
    {
        return $this->container['company'];
    }

    /**
     * Sets company
     * @param string $company Contact's company
     * @return $this
     */
    public function setCompany($company)
    {
        $this->container['company'] = $company;

        return $this;
    }

    /**
     * Gets email
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     * @param string $email Contact's email
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets created_at
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     * @param \DateTime $created_at
     * @return $this
     */
    public function setCreatedAt($created_at)
    {
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     * @return \DateTime
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     * @param \DateTime $updated_at
     * @return $this
     */
    public function setUpdatedAt($updated_at)
    {
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets deleted_at
     * @return \DateTime
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     * @param \DateTime $deleted_at
     * @return $this
     */
    public function setDeletedAt($deleted_at)
    {
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets timezone
     * @return string
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     * @param string $timezone
     * @return $this
     */
    public function setTimezone($timezone)
    {
        $allowed_values = $this->getTimezoneAllowableValues();
        if (!is_null($timezone) && !in_array($timezone, $allowed_values)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value for 'timezone', must be one of '%s'",
                    implode("', '", $allowed_values)
                )
            );
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets number
     * @return string
     */
    public function getNumber()
    {
        return $this->container['number'];
    }

    /**
     * Sets number
     * @param string $number Contact's phone number
     * @return $this
     */
    public function setNumber($number)
    {
        $this->container['number'] = $number;

        return $this;
    }

    /**
     * Gets extension
     * @return string
     */
    public function getExtension()
    {
        return $this->container['extension'];
    }

    /**
     * Sets extension
     * @param string $extension Contact's phone extension if relevant
     * @return $this
     */
    public function setExtension($extension)
    {
        $this->container['extension'] = $extension;

        return $this;
    }

    /**
     * Gets website
     * @return string
     */
    public function getWebsite()
    {
        return $this->container['website'];
    }

    /**
     * Sets website
     * @param string $website Link to website
     * @return $this
     */
    public function setWebsite($website)
    {
        $this->container['website'] = $website;

        return $this;
    }

    /**
     * Gets address
     * @return \Swagger\Client\Model\Address
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     * @param \Swagger\Client\Model\Address $address
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets custom_fields
     * @return \Swagger\Client\Model\Keyvalue[]
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     * @param \Swagger\Client\Model\Keyvalue[] $custom_fields
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


